export type BookSlug = 'genesis' | 'exodus' | 'leviticus' | 'numbers' | 'deuteronomy' | 'joshua' | 'judges' | 'ruth' | 'samuel1' | 'samuel2' | 'kings1' | 'kings2' | 'chronicles1' | 'chronicles2' | 'ezra' | 'nehemiah' | 'esther' | 'job' | 'psalms' | 'proverbs' | 'ecclesiastes' | 'song' | 'isaiah' | 'jeremiah' | 'lamentations' | 'ezekiel' | 'daniel' | 'hosea' | 'joel' | 'amos' | 'obadiah' | 'jonah' | 'micah' | 'nahum' | 'habakkuk' | 'zephaniah' | 'haggai' | 'zechariah' | 'malachi' | 'matthew' | 'mark' | 'luke' | 'john' | 'acts' | 'romans' | 'corinthians1' | 'corinthians2' | 'galatians' | 'ephesians' | 'philippians' | 'colossians' | 'thessalonians1' | 'thessalonians2' | 'timothy1' | 'timothy2' | 'titus' | 'philemon' | 'hebrews' | 'james' | 'peter1' | 'peter2' | 'john1' | 'john2' | 'john3' | 'jude' | 'revelation';

export const BOOKS: Record<BookSlug, { name: string; total: number }> = {
  genesis: { name: '창세기', total: 50 },
  exodus: { name: '출애굽기', total: 40 },
  leviticus: { name: '레위기', total: 27 },
  numbers: { name: '민수기', total: 36 },
  deuteronomy: { name: '신명기', total: 34 },
  joshua: { name: '여호수아', total: 24 },
  judges: { name: '사사기', total: 21 },
  ruth: { name: '룻기', total: 4 },
  samuel1: { name: '사무엘상', total: 31 },
  samuel2: { name: '사무엘하', total: 24 },
  kings1: { name: '열왕기상', total: 22 },
  kings2: { name: '열왕기하', total: 25 },
  chronicles1: { name: '역대상', total: 29 },
  chronicles2: { name: '역대하', total: 36 },
  ezra: { name: '에스라', total: 10 },
  nehemiah: { name: '느헤미야', total: 13 },
  esther: { name: '에스더', total: 10 },
  job: { name: '욥기', total: 42 },
  psalms: { name: '시편', total: 150 },
  proverbs: { name: '잠언', total: 31 },
  ecclesiastes: { name: '전도서', total: 12 },
  song: { name: '아가', total: 8 },
  isaiah: { name: '이사야', total: 66 },
  jeremiah: { name: '예레미야', total: 52 },
  lamentations: { name: '예레미야애가', total: 5 },
  ezekiel: { name: '에스겔', total: 48 },
  daniel: { name: '다니엘', total: 12 },
  hosea: { name: '호세아', total: 14 },
  joel: { name: '요엘', total: 3 },
  amos: { name: '아모스', total: 9 },
  obadiah: { name: '오바댜', total: 1 },
  jonah: { name: '요나', total: 4 },
  micah: { name: '미가', total: 7 },
  nahum: { name: '나훔', total: 3 },
  habakkuk: { name: '하박국', total: 3 },
  zephaniah: { name: '스바냐', total: 3 },
  haggai: { name: '학개', total: 2 },
  zechariah: { name: '스가랴', total: 14 },
  malachi: { name: '말라기', total: 4 },
  matthew: { name: '마태복음', total: 28 },
  mark: { name: '마가복음', total: 16 },
  luke: { name: '누가복음', total: 24 },
  john: { name: '요한복음', total: 21 },
  acts: { name: '사도행전', total: 28 },
  romans: { name: '로마서', total: 16 },
  corinthians1: { name: '고린도전서', total: 16 },
  corinthians2: { name: '고린도후서', total: 13 },
  galatians: { name: '갈라디아서', total: 6 },
  ephesians: { name: '에베소서', total: 6 },
  philippians: { name: '빌립보서', total: 4 },
  colossians: { name: '골로새서', total: 4 },
  thessalonians1: { name: '데살로니가전서', total: 5 },
  thessalonians2: { name: '데살로니가후서', total: 3 },
  timothy1: { name: '디모데전서', total: 6 },
  timothy2: { name: '디모데후서', total: 4 },
  titus: { name: '디도서', total: 3 },
  philemon: { name: '빌레몬서', total: 1 },
  hebrews: { name: '히브리서', total: 13 },
  james: { name: '야고보서', total: 5 },
  peter1: { name: '베드로전서', total: 5 },
  peter2: { name: '베드로후서', total: 3 },
  john1: { name: '요한일서', total: 5 },
  john2: { name: '요한이서', total: 1 },
  john3: { name: '요한삼서', total: 1 },
  jude: { name: '유다서', total: 1 },
  revelation: { name: '요한계시록', total: 22 },
};

export const OT_BOOKS: BookSlug[] = ['genesis', 'exodus', 'leviticus', 'numbers', 'deuteronomy', 'joshua', 'judges', 'ruth', 'samuel1', 'samuel2', 'kings1', 'kings2', 'chronicles1', 'chronicles2', 'ezra', 'nehemiah', 'esther', 'job', 'psalms', 'proverbs', 'ecclesiastes', 'song', 'isaiah', 'jeremiah', 'lamentations', 'ezekiel', 'daniel', 'hosea', 'joel', 'amos', 'obadiah', 'jonah', 'micah', 'nahum', 'habakkuk', 'zephaniah', 'haggai', 'zechariah', 'malachi'];

export const NT_BOOKS: BookSlug[] = ['matthew', 'mark', 'luke', 'john', 'acts', 'romans', 'corinthians1', 'corinthians2', 'galatians', 'ephesians', 'philippians', 'colossians', 'thessalonians1', 'thessalonians2', 'timothy1', 'timothy2', 'titus', 'philemon', 'hebrews', 'james', 'peter1', 'peter2', 'john1', 'john2', 'john3', 'jude', 'revelation'];

export const BOOK_ORDER: BookSlug[] = [...OT_BOOKS, ...NT_BOOKS];
