export type BookSlug = 'genesis' | 'exodus' | 'leviticus' | 'numbers' | 'deuteronomy' | 'joshua' | 'judges' | 'ruth' | 'samuel1' | 'samuel2' | 'kings1' | 'kings2' | 'chronicles1' | 'chronicles2' | 'ezra' | 'nehemiah' | 'esther' | 'job' | 'proverbs' | 'ecclesiastes' | 'song' | 'isaiah' | 'jeremiah' | 'lamentations' | 'ezekiel' | 'daniel' | 'hosea' | 'joel' | 'amos' | 'obadiah' | 'jonah' | 'micah' | 'nahum' | 'habakkuk' | 'zephaniah' | 'haggai' | 'zechariah' | 'malachi';

export const BOOKS: Record<BookSlug, { name: string; total: number }> = {
  genesis: { name: '창세기', total: 50 },
  exodus: { name: '출애굽기', total: 40 },
  leviticus: { name: '레위기', total: 27 },
  numbers: { name: '민수기', total: 36 },
  deuteronomy: { name: '신명기', total: 34 },
  joshua: { name: '여호수아', total: 24 },
  judges: { name: '사사기', total: 21 },
  ruth: { name: '룻기', total: 4 },
  samuel1: { name: '사무엘상', total: 31 },
  samuel2: { name: '사무엘하', total: 24 },
  kings1: { name: '열왕기상', total: 22 },
  kings2: { name: '열왕기하', total: 25 },
  chronicles1: { name: '역대상', total: 29 },
  chronicles2: { name: '역대하', total: 36 },
  ezra: { name: '에스라', total: 10 },
  nehemiah: { name: '느헤미야', total: 13 },
  esther: { name: '에스더', total: 10 },
  job: { name: '욥기', total: 42 },
  proverbs: { name: '잠언', total: 31 },
  ecclesiastes: { name: '전도서', total: 12 },
  song: { name: '아가', total: 8 },
  isaiah: { name: '이사야', total: 66 },
  jeremiah: { name: '예레미야', total: 52 },
  lamentations: { name: '예레미야애가', total: 5 },
  ezekiel: { name: '에스겔', total: 48 },
  daniel: { name: '다니엘', total: 12 },
  hosea: { name: '호세아', total: 14 },
  joel: { name: '요엘', total: 3 },
  amos: { name: '아모스', total: 9 },
  obadiah: { name: '오바댜', total: 1 },
  jonah: { name: '요나', total: 4 },
  micah: { name: '미가', total: 7 },
  nahum: { name: '나훔', total: 3 },
  habakkuk: { name: '하박국', total: 3 },
  zephaniah: { name: '스바냐', total: 3 },
  haggai: { name: '학개', total: 2 },
  zechariah: { name: '스가랴', total: 14 },
  malachi: { name: '말라기', total: 4 },
};

export const BOOK_ORDER: BookSlug[] = ['genesis', 'exodus', 'leviticus', 'numbers', 'deuteronomy', 'joshua', 'judges', 'ruth', 'samuel1', 'samuel2', 'kings1', 'kings2', 'chronicles1', 'chronicles2', 'ezra', 'nehemiah', 'esther', 'job', 'proverbs', 'ecclesiastes', 'song', 'isaiah', 'jeremiah', 'lamentations', 'ezekiel', 'daniel', 'hosea', 'joel', 'amos', 'obadiah', 'jonah', 'micah', 'nahum', 'habakkuk', 'zephaniah', 'haggai', 'zechariah', 'malachi'];
