import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const chapter = z.object({
  chapter: z.number(),
  title: z.string(),
  emoji: z.string().optional().default(''),
});

const intro = z.object({
  title: z.string(),
  bookName: z.string(),
  emoji: z.string().optional().default(''),
  author: z.string().optional(),
  era: z.string().optional(),
  themes: z.array(z.string()).optional(),
});



export const collections = {
  genesis: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/genesis' }),
    schema: chapter,
  }),
  exodus: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/exodus' }),
    schema: chapter,
  }),
  leviticus: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/leviticus' }),
    schema: chapter,
  }),
  numbers: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/numbers' }),
    schema: chapter,
  }),
  deuteronomy: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/deuteronomy' }),
    schema: chapter,
  }),
  joshua: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/joshua' }),
    schema: chapter,
  }),
  judges: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/judges' }),
    schema: chapter,
  }),
  ruth: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/ruth' }),
    schema: chapter,
  }),
  samuel1: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/samuel1' }),
    schema: chapter,
  }),
  samuel2: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/samuel2' }),
    schema: chapter,
  }),
  kings1: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/kings1' }),
    schema: chapter,
  }),
  kings2: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/kings2' }),
    schema: chapter,
  }),
  chronicles1: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/chronicles1' }),
    schema: chapter,
  }),
  chronicles2: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/chronicles2' }),
    schema: chapter,
  }),
  ezra: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/ezra' }),
    schema: chapter,
  }),
  nehemiah: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/nehemiah' }),
    schema: chapter,
  }),
  esther: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/esther' }),
    schema: chapter,
  }),
  job: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/job' }),
    schema: chapter,
  }),
  psalms: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/psalms' }), schema: chapter }),
  proverbs: defineCollection({
    loader: glob({ pattern: '*.md', base: './src/content/proverbs' }),
    schema: chapter,
  }),
  ecclesiastes: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/ecclesiastes' }), schema: chapter }),
  song: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/song' }), schema: chapter }),
  isaiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/isaiah' }), schema: chapter }),
  jeremiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/jeremiah' }), schema: chapter }),
  lamentations: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/lamentations' }), schema: chapter }),
  ezekiel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/ezekiel' }), schema: chapter }),
  daniel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/daniel' }), schema: chapter }),
  hosea: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/hosea' }), schema: chapter }),
  joel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/joel' }), schema: chapter }),
  amos: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/amos' }), schema: chapter }),
  obadiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/obadiah' }), schema: chapter }),
  jonah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/jonah' }), schema: chapter }),
  micah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/micah' }), schema: chapter }),
  nahum: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/nahum' }), schema: chapter }),
  habakkuk: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/habakkuk' }), schema: chapter }),
  zephaniah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/zephaniah' }), schema: chapter }),
  haggai: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/haggai' }), schema: chapter }),
  zechariah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/zechariah' }), schema: chapter }),
  malachi: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/malachi' }), schema: chapter }),
  matthew: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/matthew' }), schema: chapter }),
  mark: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/mark' }), schema: chapter }),
  luke: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/luke' }), schema: chapter }),
  john: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/john' }), schema: chapter }),
  acts: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/acts' }), schema: chapter }),
  romans: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/romans' }), schema: chapter }),
  corinthians1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/corinthians1' }), schema: chapter }),
  corinthians2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/corinthians2' }), schema: chapter }),
  galatians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/galatians' }), schema: chapter }),
  ephesians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/ephesians' }), schema: chapter }),
  philippians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/philippians' }), schema: chapter }),
  colossians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/colossians' }), schema: chapter }),
  thessalonians1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/thessalonians1' }), schema: chapter }),
  thessalonians2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/thessalonians2' }), schema: chapter }),
  timothy1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/timothy1' }), schema: chapter }),
  timothy2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/timothy2' }), schema: chapter }),
  titus: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/titus' }), schema: chapter }),
  philemon: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/philemon' }), schema: chapter }),
  hebrews: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/hebrews' }), schema: chapter }),
  james: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/james' }), schema: chapter }),
  peter1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/peter1' }), schema: chapter }),
  peter2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/peter2' }), schema: chapter }),
  john1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/john1' }), schema: chapter }),
  john2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/john2' }), schema: chapter }),
  john3: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/john3' }), schema: chapter }),
  jude: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/jude' }), schema: chapter }),
  revelation: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/revelation' }), schema: chapter }),
  harmony: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/harmony' }), schema: chapter }),
  kidsbGenesis: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-genesis' }), schema: chapter }),
  kidsbExodus: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-exodus' }), schema: chapter }),
  kidsbLeviticus: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-leviticus' }), schema: chapter }),
  kidsbNumbers: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-numbers' }), schema: chapter }),
  kidsbDeuteronomy: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-deuteronomy' }), schema: chapter }),
  kidsbJoshua: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-joshua' }), schema: chapter }),
  kidsbJudges: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-judges' }), schema: chapter }),
  kidsbRuth: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-ruth' }), schema: chapter }),
  kidsbSamuel1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-samuel1' }), schema: chapter }),
  kidsbSamuel2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-samuel2' }), schema: chapter }),
  kidsbKings1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-kings1' }), schema: chapter }),
  kidsbKings2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-kings2' }), schema: chapter }),
  kidsbChronicles1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-chronicles1' }), schema: chapter }),
  kidsbChronicles2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-chronicles2' }), schema: chapter }),
  kidsbEzra: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-ezra' }), schema: chapter }),
  kidsbNehemiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-nehemiah' }), schema: chapter }),
  kidsbEsther: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-esther' }), schema: chapter }),
  kidsbJob: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-job' }), schema: chapter }),
  kidsbPsalms: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-psalms' }), schema: chapter }),
  kidsbProverbs: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-proverbs' }), schema: chapter }),
  kidsbEcclesiastes: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-ecclesiastes' }), schema: chapter }),
  kidsbSong: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-song' }), schema: chapter }),
  kidsbIsaiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-isaiah' }), schema: chapter }),
  kidsbJeremiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-jeremiah' }), schema: chapter }),
  kidsbLamentations: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-lamentations' }), schema: chapter }),
  kidsbEzekiel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-ezekiel' }), schema: chapter }),
  kidsbDaniel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-daniel' }), schema: chapter }),
  kidsbHosea: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-hosea' }), schema: chapter }),
  kidsbJoel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-joel' }), schema: chapter }),
  kidsbAmos: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-amos' }), schema: chapter }),
  kidsbObadiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-obadiah' }), schema: chapter }),
  kidsbJonah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-jonah' }), schema: chapter }),
  kidsbMicah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-micah' }), schema: chapter }),
  kidsbNahum: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-nahum' }), schema: chapter }),
  kidsbHabakkuk: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-habakkuk' }), schema: chapter }),
  kidsbZephaniah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-zephaniah' }), schema: chapter }),
  kidsbHaggai: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-haggai' }), schema: chapter }),
  kidsbZechariah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-zechariah' }), schema: chapter }),
  kidsbMalachi: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-malachi' }), schema: chapter }),
  kidsbMatthew: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-matthew' }), schema: chapter }),
  kidsbMark: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-mark' }), schema: chapter }),
  kidsbLuke: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-luke' }), schema: chapter }),
  kidsbJohn: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-john' }), schema: chapter }),
  kidsbActs: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-acts' }), schema: chapter }),
  kidsbRomans: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-romans' }), schema: chapter }),
  kidsbCorinthians1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-corinthians1' }), schema: chapter }),
  kidsbCorinthians2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-corinthians2' }), schema: chapter }),
  kidsbGalatians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-galatians' }), schema: chapter }),
  kidsbEphesians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-ephesians' }), schema: chapter }),
  kidsbPhilippians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-philippians' }), schema: chapter }),
  kidsbColossians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-colossians' }), schema: chapter }),
  kidsbThessalonians1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-thessalonians1' }), schema: chapter }),
  kidsbThessalonians2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-thessalonians2' }), schema: chapter }),
  kidsbTimothy1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-timothy1' }), schema: chapter }),
  kidsbTimothy2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-timothy2' }), schema: chapter }),
  kidsbTitus: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-titus' }), schema: chapter }),
  kidsbPhilemon: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-philemon' }), schema: chapter }),
  kidsbHebrews: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-hebrews' }), schema: chapter }),
  kidsbJames: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-james' }), schema: chapter }),
  kidsbPeter1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-peter1' }), schema: chapter }),
  kidsbPeter2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-peter2' }), schema: chapter }),
  kidsbJohn1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-john1' }), schema: chapter }),
  kidsbJohn2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-john2' }), schema: chapter }),
  kidsbJohn3: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-john3' }), schema: chapter }),
  kidsbJude: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-jude' }), schema: chapter }),
  kidsbRevelation: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-revelation' }), schema: chapter }),
  krvGenesis: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-genesis' }), schema: chapter }),
  krvExodus: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-exodus' }), schema: chapter }),
  krvLeviticus: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-leviticus' }), schema: chapter }),
  krvNumbers: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-numbers' }), schema: chapter }),
  krvDeuteronomy: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-deuteronomy' }), schema: chapter }),
  krvJoshua: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-joshua' }), schema: chapter }),
  krvJudges: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-judges' }), schema: chapter }),
  krvRuth: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-ruth' }), schema: chapter }),
  krvSamuel1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-samuel1' }), schema: chapter }),
  krvSamuel2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-samuel2' }), schema: chapter }),
  krvKings1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-kings1' }), schema: chapter }),
  krvKings2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-kings2' }), schema: chapter }),
  krvChronicles1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-chronicles1' }), schema: chapter }),
  krvChronicles2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-chronicles2' }), schema: chapter }),
  krvEzra: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-ezra' }), schema: chapter }),
  krvNehemiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-nehemiah' }), schema: chapter }),
  krvEsther: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-esther' }), schema: chapter }),
  krvJob: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-job' }), schema: chapter }),
  krvPsalms: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-psalms' }), schema: chapter }),
  krvProverbs: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-proverbs' }), schema: chapter }),
  krvEcclesiastes: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-ecclesiastes' }), schema: chapter }),
  krvSong: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-song' }), schema: chapter }),
  krvIsaiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-isaiah' }), schema: chapter }),
  krvJeremiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-jeremiah' }), schema: chapter }),
  krvLamentations: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-lamentations' }), schema: chapter }),
  krvEzekiel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-ezekiel' }), schema: chapter }),
  krvDaniel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-daniel' }), schema: chapter }),
  krvHosea: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-hosea' }), schema: chapter }),
  krvJoel: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-joel' }), schema: chapter }),
  krvAmos: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-amos' }), schema: chapter }),
  krvObadiah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-obadiah' }), schema: chapter }),
  krvJonah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-jonah' }), schema: chapter }),
  krvMicah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-micah' }), schema: chapter }),
  krvNahum: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-nahum' }), schema: chapter }),
  krvHabakkuk: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-habakkuk' }), schema: chapter }),
  krvZephaniah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-zephaniah' }), schema: chapter }),
  krvHaggai: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-haggai' }), schema: chapter }),
  krvZechariah: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-zechariah' }), schema: chapter }),
  krvMalachi: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-malachi' }), schema: chapter }),
  krvMatthew: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-matthew' }), schema: chapter }),
  krvMark: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-mark' }), schema: chapter }),
  krvLuke: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-luke' }), schema: chapter }),
  krvJohn: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-john' }), schema: chapter }),
  krvActs: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-acts' }), schema: chapter }),
  krvRomans: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-romans' }), schema: chapter }),
  krvCorinthians1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-corinthians1' }), schema: chapter }),
  krvCorinthians2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-corinthians2' }), schema: chapter }),
  krvGalatians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-galatians' }), schema: chapter }),
  krvEphesians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-ephesians' }), schema: chapter }),
  krvPhilippians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-philippians' }), schema: chapter }),
  krvColossians: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-colossians' }), schema: chapter }),
  krvThessalonians1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-thessalonians1' }), schema: chapter }),
  krvThessalonians2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-thessalonians2' }), schema: chapter }),
  krvTimothy1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-timothy1' }), schema: chapter }),
  krvTimothy2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-timothy2' }), schema: chapter }),
  krvTitus: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-titus' }), schema: chapter }),
  krvPhilemon: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-philemon' }), schema: chapter }),
  krvHebrews: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-hebrews' }), schema: chapter }),
  krvJames: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-james' }), schema: chapter }),
  krvPeter1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-peter1' }), schema: chapter }),
  krvPeter2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-peter2' }), schema: chapter }),
  krvJohn1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-john1' }), schema: chapter }),
  krvJohn2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-john2' }), schema: chapter }),
  krvJohn3: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-john3' }), schema: chapter }),
  krvJude: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-jude' }), schema: chapter }),
  krvRevelation: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/krv-revelation' }), schema: chapter }),
  tobit: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/tobit' }), schema: chapter }),
  kidsbTobit: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-tobit' }), schema: chapter }),
  judith: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/judith' }), schema: chapter }),
  kidsbJudith: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-judith' }), schema: chapter }),
  maccabees1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/maccabees1' }), schema: chapter }),
  kidsbMaccabees1: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-maccabees1' }), schema: chapter }),
  maccabees2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/maccabees2' }), schema: chapter }),
  kidsbMaccabees2: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-maccabees2' }), schema: chapter }),
  wisdom: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/wisdom' }), schema: chapter }),
  kidsbWisdom: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-wisdom' }), schema: chapter }),
  sirach: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/sirach' }), schema: chapter }),
  kidsbSirach: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-sirach' }), schema: chapter }),
  baruch: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/baruch' }), schema: chapter }),
  kidsbBaruch: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-baruch' }), schema: chapter }),
  danielExtra: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/danielExtra' }), schema: chapter }),
  kidsbDanielextra: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-danielExtra' }), schema: chapter }),
  estherExtra: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/estherExtra' }), schema: chapter }),
  kidsbEstherextra: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/kidsb-estherExtra' }), schema: chapter }),
  intros: defineCollection({ loader: glob({ pattern: '*.md', base: './src/content/intros' }), schema: intro }),
};
